# Generated by Django 5.1.6 on 2025-02-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLL_Cases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cases', models.CharField(max_length=3)),
                ('algorithm', models.CharField(max_length=100)),
            ],
        ),
    ]
