# Generated by Django 5.1.6 on 2025-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pllcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pll_cases',
            name='setup',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
